### ISSUE TITLE
Readme showing up as Lab

### ISSUE THREAD

**Issue by zacscodingclub** [learn-co-students/react-components-events-actions-and-stores-v-000#1]
This lesson is showing up as a Lab, requiring students to pass tests and submit the lesson before continuing.  Tagging @aturkewi and will ship a link in Slack

<img width="800" alt="screen shot 2017-02-22 at 2 55 07 pm" src="https://cloud.githubusercontent.com/assets/7807203/23229625/f61bae04-f90e-11e6-823f-3f7a5ead3089.png">

**Comment by aturkewi** [comment]
This is showing up as a readme now and should be all set. Thanks!
